services:
  db:
    image: postgres:16
    container_name: callba_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: callba
    ports:
      - "5432:5432"
    volumes:
      - callba_pgdata:/var/lib/postgresql/data

volumes:
  callba_pgdata:
